Repository FossifyOrg/Phone, pull requests merged in 2025-06, with the labels that each got.

#419 chore(l10n): update translations
  app/src/main/res/values-iw/strings.xml
Labels: l10n

#420 ci: update release workflows
  .github/workflows/foss-release.yml
  .github/workflows/gplay-release.yml
  .github/workflows/pr.yml
  .github/workflows/prepare-release-pr.yml
  .github/workflows/release-commenter.yml
  .github/workflows/release.yml
  .github/workflows/testing-build.yml
Labels: ci

#423 ci: add fastlane metadata validation and update release trigger
  .github/dependabot.yml
  .github/workflows/prepare-release-pr.yml
  .github/workflows/validate-fastlane-metadata.yml
  CODEOWNERS
Labels: ci

#424 fix: ensure unique ID for date headers
  CHANGELOG.md
  app/src/main/kotlin/org/fossify/phone/activities/CallActivity.kt
  app/src/main/kotlin/org/fossify/phone/models/CallLogItem.kt
Labels: testers needed
